import os
from openai import OpenAI
from app.core.database import get_db_connection
from app.repository.pgvector_retriever import PGVectorRetriever
from app.services.judge_service import JudgeService
from app.services.token_tracker import TokenMetrics, calculate_bytes


class RAGService:
    def __init__(self, retriever=None):
        self.client = OpenAI(
            base_url=os.getenv("PRIVATEMODE_PROXY_URL", "http://localhost:8080/v1"),
            api_key=os.getenv("PRIVATEMODE_API_KEY", "placeholder"),
        )
        self.model = os.getenv("PRIVATEMODE_MODEL", "meta-llama-3.3-70b")
        self.retriever = retriever if retriever is not None else PGVectorRetriever()
        self.judge_service = JudgeService(self)

    def generate_answer_with_citations(self, query: str, retrieved_contexts: list) -> dict:
        # Construct the context block with explicit metadata IDs
        context_str = ""
        for i, ctx in enumerate(retrieved_contexts):
            context_str += f"[Source #{i+1}]: {ctx['article']} - {ctx['paragraph']} (Page {ctx['page']})\nContent: {ctx['text']}\n\n"

        system_prompt = (
            "You are an expert AI Legal Advisor specialized in the EU AI Act.\n"
            "Answer the user's question using ONLY the provided sources. For every factual claim "
            "you make, append an inline citation in the format [Source #X]. At the end of your response, "
            "provide a 'Sources and Trustworthiness' section listing the exact Article, Paragraph, and Page."
        )

        # Record incoming data size
        bytes_in = calculate_bytes(system_prompt + context_str + query)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Context:\n{context_str}\n\nQuestion: {query}"}
                ],
                temperature=0.1
            )

            raw_output = response.choices[0].message.content
            usage = response.usage
            prompt_tokens = usage.prompt_tokens
            completion_tokens = usage.completion_tokens
            total_tokens = usage.total_tokens
        except Exception:
            fallback_summary = "\n\n".join(
                f"[Source #{i+1}] {ctx.get('article', 'Unknown')} - paragraph {ctx.get('paragraph', 'n/a')} (Page {ctx.get('page', '?')})\n{ctx.get('text', '')}"
                for i, ctx in enumerate(retrieved_contexts)
            )
            raw_output = (
                "This response is a local fallback because the configured model endpoint is currently unavailable. "
                "It is grounded in the retrieved sources shown below, but it is not generated by the remote model.\n\n"
                + fallback_summary
            )
            prompt_tokens = 0
            completion_tokens = 0
            total_tokens = 0

        bytes_out = calculate_bytes(raw_output)
        metrics = TokenMetrics(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            bytes_in=bytes_in,
            bytes_out=bytes_out
        )

        return {
            "answer": raw_output,
            "metrics": metrics,
        }

    def search(self, query: str, limit: int = 4) -> list:
        if self.retriever is not None:
            return self.retriever.search(query, limit=limit)

        conn = get_db_connection()
        try:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT content, document_name, article, page_number
                    FROM document_chunks
                    ORDER BY id
                    LIMIT %s
                    """,
                    (limit,),
                )
                rows = cur.fetchall()
        finally:
            conn.close()

        return [
            {
                "text": row[0],
                "document_name": row[1],
                "article": row[2],
                "page": row[3],
                "paragraph": "",
            }
            for row in rows
        ]

    def answer_query(self, query: str, limit: int = 4) -> dict:
        retrieved_contexts = self.search(query, limit=limit)
        result = self.generate_answer_with_citations(query, retrieved_contexts)
        context_text = "\n\n".join(
            f"[{i + 1}] {ctx.get('article', 'Unknown')} | page {ctx.get('page', '?')} | {ctx.get('text', '')}"
            for i, ctx in enumerate(retrieved_contexts)
        )
        judge_result = self.judge_service.evaluate_response(query, context_text, result["answer"])
        if not isinstance(judge_result, dict):
            judge_result = {
                "faithfulness_score": 0.0,
                "relevance_score": 0.0,
                "explanation": "Judge unavailable",
            }
        return {
            "answer": result["answer"],
            "sources": retrieved_contexts,
            "metrics": result["metrics"],
            "judge": judge_result,
            "token_usage": {
                "prompt_tokens": result["metrics"].prompt_tokens,
                "completion_tokens": result["metrics"].completion_tokens,
                "total_tokens": result["metrics"].total_tokens,
            },
        }